console.log('1 + "2" = ', 1 + "2");
console.log('"5" - 3 = ', "5" - 3);
console.log('true + 1 = ', true + 1);
console.log('false + 1 = ', false + 1);
console.log('null + 1 = ', null + 1);
console.log('undefined + 1 = ', undefined + 1); 
console.log('null == undefined = ', null == undefined);
console.log('null === undefined = ', null === undefined);
console.log('"5" == 5 = ', "5" == 5); 
console.log('"5" === 5 = ', "5" === 5);
console.log('0 == false = ', 0 == false); 
console.log('0 === false = ', 0 === false);
console.log('"0" == false = ', "0" == false);
console.log('"0" === false = ', "0" === false);
console.log('1 + "2" - 3 = ', 1 + "2" - 3);
console.log('"10" * "2" = ', "10" * "2");
console.log('"10" / 2 = ', "10" / 2);
console.log('"10" % 3 = ', "10" % 3);
console.log('true == 1 = ', true == 1);
console.log('false == 0 = ', false == 0);
console.log('true === 1 = ', true === 1);
console.log('false === 0 = ', false === 0);
console.log('null == 0 = ', null == 0);
console.log('null === 0 = ', null === 0);
console.log('undefined == 0 = ', undefined == 0);
console.log('undefined === 0 = ', undefined === 0);
console.log('"5" + null = ', "5" + null);
console.log('"5" + undefined = ', "5" + undefined);
console.log('5 + null = ', 5 + null);
console.log('5 + undefined = ', 5 + undefined);
console.log('"5" - null = ', "5" - null);
console.log('"5" - undefined = ', "5" - undefined);
console.log('"5" * null = ', "5" * null);
console.log('"5" * undefined = ', "5" * undefined);
console.log('"5" / null = ', "5" / null);
console.log('"5" / undefined = ', "5" / undefined);
console.log('[] == 0 = ', [] == 0);
console.log('[] == "" = ', [] == "");
console.log('[] + {} = ', [] + {});
console.log('{} + [] = ', {} + []);
console.log('![] = ', ![]);
console.log('!![] = ', !![]);
console.log('!{} = ', !{});
console.log('!!{} = ', !!{});
console.log('"" == 0 = ', "" == 0);
console.log('"" === 0 = ', "" === 0);
console.log('"true" == true = ', "true" == true);
console.log('"false" == false = ', "false" == false);
console.log('Boolean("false") = ', Boolean("false"));
console.log('Boolean("") = ', Boolean(""));
console.log('Boolean(0) = ', Boolean(0));
console.log('Boolean("0") = ', Boolean("0"));
console.log('NaN == NaN = ', NaN == NaN);
console.log('isNaN(NaN) = ', isNaN(NaN));
console.log('typeof NaN = ', typeof NaN);
console.log('typeof null = ', typeof null);
console.log('typeof undefined = ', typeof undefined);
console.log('typeof [] = ', typeof []);
console.log('typeof {} = ', typeof {});
console.log('typeof function(){} = ', typeof function(){});
console.log('parseInt("123abc") = ', parseInt("123abc"));
console.log('parseFloat("123.45px") = ', parseFloat("123.45px"));
console.log('Number("123abc") = ', Number("123abc"));
console.log('Number("123.45px") = ', Number("123.45px"));
console.log('!!"false" = ', !!"false");
console.log('!!"0" = ', !!"0");
console.log('[] == false = ', [] == false);
console.log('[1] == true = ', [1] == true);
console.log('[0] == false = ', [0] == false);
console.log('[] == ![] = ', [] == ![]);
console.log('null == false = ', null == false);
console.log('undefined == false = ', undefined == false);
console.log('null == NaN = ', null == NaN);
console.log('undefined == NaN = ', undefined == NaN);
console.log('false == NaN = ', false == NaN);
console.log('true == NaN = ', true == NaN);

console.log('Symbol("a") === Symbol("a") = ', Symbol("a") === Symbol("a"));
console.log('[2] + [3] = ', [2] + [3]);
console.log('new String("5") == "5" = ', new String("5") == "5");
console.log('new Number(5) === 5 = ', new Number(5) === 5);
console.log('{} == {} = ', {} == {}); 
